export default {
        
    FETCH_FLAT_RATES_START: "FETCH_FLAT_RATES_START",
    FETCH_FLAT_RATES_SUCCESS: "FETCH_FLAT_RATES_SUCCESS",
    FETCH_FLAT_RATES_FAILURE: "FETCH_FLAT_RATES_FAILURE",

    CREATE_FLAT_RATE_START: "CREATE_FLAT_RATE_START",
    CREATE_FLAT_RATE_SUCCESS: "CREATE_FLAT_RATE_SUCCESS",
    CREATE_FLAT_RATE_FAILURE: "CREATE_FLAT_RATE_FAILURE",

    DELETE_FLAT_RATE_START: "DELETE_FLAT_RATE_START",
    DELETE_FLAT_RATE_SUCCESS: "DELETE_FLAT_RATE_SUCCESS",
    DELETE_FLAT_RATE_FAILURE: "DELETE_FLAT_RATE_FAILURE",

    UPDATE_FLAT_RATE_START: "UPDATE_FLAT_RATE_START",
    UPDATE_FLAT_RATE_SUCCESS: "UPDATE_FLAT_RATE_SUCCESS",
    UPDATE_FLAT_RATE_FAILURE: "UPDATE_FLAT_RATE_FAILURE",

    FETCH_PROFILE_START: "FETCH_PROFILE_START",
    FETCH_PROFILE_SUCCESS: "FETCH_PROFILE_SUCCESS",
    FETCH_PROFILE_FAILURE: "FETCH_PROFILE_FAILURE",
    
    UPDATE_COMPANY_DETAILS_START: "UPDATE_COMPANY_DETAILS_START",
    UPDATE_COMPANY_DETAILS_SUCCESS: "UPDATE_COMPANY_DETAILS_SUCCESS",
    UPDATE_COMPANY_DETAILS_FAILURE: "UPDATE_COMPANY_DETAILS_FAILURE",

    UPDATE_MANAGER_DETAILS_START: "UPDATE_MANAGER_DETAILS_START",
    UPDATE_MANAGER_DETAILS_SUCCESS: "UPDATE_MANAGER_DETAILS_SUCCESS",
    UPDATE_MANAGER_DETAILS_FAILURE: "UPDATE_MANAGER_DETAILS_FAILURE",

};